version: 2.1
setup: true
orbs:
  docker: circleci/docker@1.7.0
executors:
  default:
    docker:
      - image: cimg/base:stable  # Or use cimg/python, cimg/node, etc., as per your project needs

workflows:
  version: 2
  build_push:
    jobs:
      - docker/publish:
          deploy: true 
          docker-username: DOCKER_USERNAME 
          image: $DOCKER_IMAGE