version: 2.1
setup: true
orbs:
  docker: circleci/docker@1.7.0


workflows:
  version: 2
  build_push:
    jobs:
      - docker/publish:
          deploy: true 
          docker-username: DOCKER_USERNAME 
          image: $DOCKER_IMAGE