version: 2.1

jobs:
  build_test_push:
    machine:
      image: ubuntu-2204:current  # Use a machine executor with Ubuntu
    steps:
      - checkout  # Checkout the source code
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_IMAGE:latest .
      

      - run:
          name: Test Docker Image
          command: |
            docker run -d --name my-app --rm -p 8080:8080 $DOCKER_IMAGE:latest
            sleep 5
            curl http://localhost:8080
            docker stop my-app
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_IMAGE:latest
  
workflows:
  version: 2
  build_test_push:
    jobs:
      - build_test_push